### ISSUE TITLE
bug in lower android version(Lollipop)

### ISSUE THREAD

**Issue by StormLion** [florinmuscalu/FM_Score#3]
Hi, I find some bug in Android Lollipop.
First, just like the image blow, the title bar cover over the FM_Score view, but in fact I not cover it in my layout file.
![img](https://user-images.githubusercontent.com/8315922/115117791-df1b7800-9fd2-11eb-9883-d89c158cebe1.png)
blow is some code of my layout file
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:fbutton="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/white"
    android:orientation="vertical"
    android:id="@+id/pv_scroll">
    <ro.coreengine.music_score.FM_Score
        android:id="@+id/rp_keyboard_stave"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="7"/>
    <LinearLayout
        android:id="@+id/rp_keyboard_panel"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="4"
        android:orientation="vertical"
        android:layout_marginTop="5dp">`

Second, I want to show DO RE MI FA, In higher android version, it's good, but in Lollipop, the same json file is show in a wrong order(Just like the image above). Hope you can help to solve these bug, thanks in advance!

**Comment by florinmuscalu** [comment]
Hi,
Sorry, I somehow missed you message. I will look into it, tbh I did not try it on older version of Android.
Thanks,
Florin.

**Comment by florinmuscalu** [comment]
So I checked, and indeed it's not good on Lollipop... I don't think it's an easy fix, and to be honest, I don't want to waste time fixing it for such an old Android version. I target at least SDK 26 (Oreo) and I believe it's enough. I'm not even sure that such old phones, using Lollipop, would have the necessary CPU horsepower.

**Comment by StormLion** [comment]
> So I checked, and indeed it's not good on Lollipop... I don't think it's an easy fix, and to be honest, I don't want to waste time fixing it for such an old Android version. I target at least SDK 26 (Oreo) and I believe it's enough. I'm not even sure that such old phones, using Lollipop, would have the necessary CPU horsepower.

ok, get it, thanks for your code>_<
